# Site settings
title: Matt Boys
email: matt.boys@gmail.com
description: mattty's personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattty.net" # the base hostname & protocol for your site
twitter_username: mattty
github_username:  mattty
permalink: none
# Build settings
markdown: kramdown
